# Generated by Django 5.0.2 on 2024-02-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hotel_app", "0002_remove_hotel_price_max_remove_hotel_price_min"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
